name: Update staging versions

# Controls when the action will run.
on:
  # Allow the workflow to be manually triggered
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      release-type:
        # Description to be shown in the UI instead of 'stack'
        description: 'Select a release type'
        # Default value if no value is explicitly provided
        # Input does not have to be provided for the workflow to run
        type: choice
        options: 
        - first
        - patch        
        - minor        
        - major
        default: patch
        required: true

jobs:
  update-staging-version-workflow-release-candidate:
    name: Create new candidate
    uses: victorggonzalez/workflows/.github/workflows/update-staging-version.yml@main
    with:
      release-type: ${{ inputs.release-type }}
